# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1394, 716)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1394, 716))
        MainWindow.setMaximumSize(QtCore.QSize(1394, 716))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -20, 1451, 741))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);; \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(230, 230, 230); \n"
"  border: 1px solid lightgray; \n"
" padding: 30px 15px;\n"
"  border-radius: 4px;\n"
"min-width: 200px;\n"
"min-height: 50px;\n"
"\n"
"\n"
"  font: 900 12pt \"Segoe UI Black\";\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgb(245, 245, 245); \n"
"  margin-bottom: -1px; \n"
"}\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.FilterTab = QtWidgets.QWidget()
        self.FilterTab.setObjectName("FilterTab")
        self.ImagesFrame = QtWidgets.QFrame(self.FilterTab)
        self.ImagesFrame.setGeometry(QtCore.QRect(280, 50, 1121, 571))
        self.ImagesFrame.setStyleSheet("background-color: transparent;\n"
"border-radius:5px;")
        self.ImagesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImagesFrame.setObjectName("ImagesFrame")
        self.outputImageLabel = QtWidgets.QLabel(self.ImagesFrame)
        self.outputImageLabel.setGeometry(QtCore.QRect(750, 10, 191, 31))
        self.outputImageLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel.setObjectName("outputImageLabel")
        self.inputImageLabel = QtWidgets.QLabel(self.ImagesFrame)
        self.inputImageLabel.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.inputImageLabel.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel.setObjectName("inputImageLabel")
        self.activeContour_inputImage = QtWidgets.QLabel(self.ImagesFrame)
        self.activeContour_inputImage.setGeometry(QtCore.QRect(20, 50, 512, 512))
        self.activeContour_inputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.activeContour_inputImage.setText("")
        self.activeContour_inputImage.setScaledContents(True)
        self.activeContour_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.activeContour_inputImage.setObjectName("activeContour_inputImage")
        self.activeContour_outputImage = QtWidgets.QLabel(self.ImagesFrame)
        self.activeContour_outputImage.setGeometry(QtCore.QRect(580, 50, 512, 512))
        self.activeContour_outputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.activeContour_outputImage.setText("")
        self.activeContour_outputImage.setScaledContents(True)
        self.activeContour_outputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.activeContour_outputImage.setObjectName("activeContour_outputImage")
        self.RefreshButton = QtWidgets.QPushButton(self.FilterTab)
        self.RefreshButton.setGeometry(QtCore.QRect(1250, 20, 121, 51))
        self.RefreshButton.setStyleSheet("QPushButton{\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/convert_color_to_gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RefreshButton.setIcon(icon)
        self.RefreshButton.setIconSize(QtCore.QSize(50, 50))
        self.RefreshButton.setObjectName("RefreshButton")
        self.Filtering = QtWidgets.QWidget(self.FilterTab)
        self.Filtering.setGeometry(QtCore.QRect(10, 60, 271, 471))
        self.Filtering.setStyleSheet("QWidget{\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"}")
        self.Filtering.setObjectName("Filtering")
        self.ActiveContourButton = QtWidgets.QPushButton(self.Filtering)
        self.ActiveContourButton.setGeometry(QtCore.QRect(10, 390, 221, 51))
        self.ActiveContourButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.ActiveContourButton.setObjectName("ActiveContourButton")
        self.alphaSlider = QtWidgets.QSlider(self.Filtering)
        self.alphaSlider.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.alphaSlider.setMaximum(200)
        self.alphaSlider.setSingleStep(1)
        self.alphaSlider.setPageStep(1)
        self.alphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlider.setObjectName("alphaSlider")
        self.label_5 = QtWidgets.QLabel(self.Filtering)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.label_5.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"border: none;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Filtering)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 71, 31))
        self.label_6.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"border: none;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Filtering)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 71, 31))
        self.label_7.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"border: none;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.Filtering)
        self.label_8.setGeometry(QtCore.QRect(10, 310, 71, 31))
        self.label_8.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"border: none;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Filtering)
        self.label_9.setGeometry(QtCore.QRect(10, 220, 131, 51))
        self.label_9.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"border: none;")
        self.label_9.setObjectName("label_9")
        self.betaSlider = QtWidgets.QSlider(self.Filtering)
        self.betaSlider.setGeometry(QtCore.QRect(80, 110, 160, 22))
        self.betaSlider.setMaximum(200)
        self.betaSlider.setPageStep(1)
        self.betaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.betaSlider.setObjectName("betaSlider")
        self.gammaSlider = QtWidgets.QSlider(self.Filtering)
        self.gammaSlider.setGeometry(QtCore.QRect(80, 180, 160, 22))
        self.gammaSlider.setMaximum(200)
        self.gammaSlider.setPageStep(1)
        self.gammaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gammaSlider.setObjectName("gammaSlider")
        self.iterationSlider = QtWidgets.QSlider(self.Filtering)
        self.iterationSlider.setGeometry(QtCore.QRect(80, 280, 160, 22))
        self.iterationSlider.setMinimum(1)
        self.iterationSlider.setMaximum(800)
        self.iterationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.iterationSlider.setObjectName("iterationSlider")
        self.sigmaSlider = QtWidgets.QSlider(self.Filtering)
        self.sigmaSlider.setGeometry(QtCore.QRect(90, 350, 160, 22))
        self.sigmaSlider.setMinimum(1)
        self.sigmaSlider.setMaximum(200)
        self.sigmaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sigmaSlider.setObjectName("sigmaSlider")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/FilterIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.FilterTab, icon1, "")
        self.EdgeDetection = QtWidgets.QWidget()
        self.EdgeDetection.setObjectName("EdgeDetection")
        self.ImagesFrame_2 = QtWidgets.QFrame(self.EdgeDetection)
        self.ImagesFrame_2.setGeometry(QtCore.QRect(280, 50, 1121, 571))
        self.ImagesFrame_2.setStyleSheet("background-color: transparent;\n"
"border-radius:5px;")
        self.ImagesFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagesFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ImagesFrame_2.setObjectName("ImagesFrame_2")
        self.outputImageLabel_2 = QtWidgets.QLabel(self.ImagesFrame_2)
        self.outputImageLabel_2.setGeometry(QtCore.QRect(750, 10, 191, 31))
        self.outputImageLabel_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel_2.setObjectName("outputImageLabel_2")
        self.inputImageLabel_2 = QtWidgets.QLabel(self.ImagesFrame_2)
        self.inputImageLabel_2.setGeometry(QtCore.QRect(170, 10, 191, 31))
        self.inputImageLabel_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_2.setObjectName("inputImageLabel_2")
        self.EdgeDetection_inputImage = QtWidgets.QLabel(self.ImagesFrame_2)
        self.EdgeDetection_inputImage.setGeometry(QtCore.QRect(20, 50, 512, 512))
        self.EdgeDetection_inputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.EdgeDetection_inputImage.setText("")
        self.EdgeDetection_inputImage.setScaledContents(True)
        self.EdgeDetection_inputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.EdgeDetection_inputImage.setObjectName("EdgeDetection_inputImage")
        self.EdgeDetection_outputImage = QtWidgets.QLabel(self.ImagesFrame_2)
        self.EdgeDetection_outputImage.setGeometry(QtCore.QRect(580, 50, 512, 512))
        self.EdgeDetection_outputImage.setStyleSheet("border: 4px solid black;\n"
"")
        self.EdgeDetection_outputImage.setText("")
        self.EdgeDetection_outputImage.setScaledContents(True)
        self.EdgeDetection_outputImage.setAlignment(QtCore.Qt.AlignCenter)
        self.EdgeDetection_outputImage.setObjectName("EdgeDetection_outputImage")
        self.Prewitt = QtWidgets.QWidget(self.EdgeDetection)
        self.Prewitt.setGeometry(QtCore.QRect(20, 100, 251, 111))
        self.Prewitt.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Prewitt.setObjectName("Prewitt")
        self.PrewittButton = QtWidgets.QPushButton(self.Prewitt)
        self.PrewittButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.PrewittButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.PrewittButton.setObjectName("PrewittButton")
        self.label = QtWidgets.QLabel(self.Prewitt)
        self.label.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Robert = QtWidgets.QWidget(self.EdgeDetection)
        self.Robert.setGeometry(QtCore.QRect(20, 220, 251, 121))
        self.Robert.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Robert.setObjectName("Robert")
        self.label_2 = QtWidgets.QLabel(self.Robert)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_2.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.RobetButton = QtWidgets.QPushButton(self.Robert)
        self.RobetButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.RobetButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.RobetButton.setObjectName("RobetButton")
        self.Sobel = QtWidgets.QWidget(self.EdgeDetection)
        self.Sobel.setGeometry(QtCore.QRect(20, 360, 251, 121))
        self.Sobel.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Sobel.setObjectName("Sobel")
        self.label_3 = QtWidgets.QLabel(self.Sobel)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.SobelButton = QtWidgets.QPushButton(self.Sobel)
        self.SobelButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.SobelButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.SobelButton.setObjectName("SobelButton")
        self.Canny = QtWidgets.QWidget(self.EdgeDetection)
        self.Canny.setGeometry(QtCore.QRect(20, 490, 251, 121))
        self.Canny.setStyleSheet("border: 2px solid;\n"
"border-radius: 5px;")
        self.Canny.setObjectName("Canny")
        self.label_4 = QtWidgets.QLabel(self.Canny)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 241, 31))
        self.label_4.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.CannyButton = QtWidgets.QPushButton(self.Canny)
        self.CannyButton.setGeometry(QtCore.QRect(20, 50, 211, 51))
        self.CannyButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.CannyButton.setObjectName("CannyButton")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/edge_detection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.EdgeDetection, icon2, "")
        self.PassTab = QtWidgets.QWidget()
        self.PassTab.setObjectName("PassTab")
        self.outputImageLabel_7 = QtWidgets.QLabel(self.PassTab)
        self.outputImageLabel_7.setGeometry(QtCore.QRect(1000, 50, 191, 31))
        self.outputImageLabel_7.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.outputImageLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.outputImageLabel_7.setObjectName("outputImageLabel_7")
        self.inputImageLabel_11 = QtWidgets.QLabel(self.PassTab)
        self.inputImageLabel_11.setGeometry(QtCore.QRect(420, 50, 191, 31))
        self.inputImageLabel_11.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;")
        self.inputImageLabel_11.setAlignment(QtCore.Qt.AlignCenter)
        self.inputImageLabel_11.setObjectName("inputImageLabel_11")
        self.hough_input = QtWidgets.QLabel(self.PassTab)
        self.hough_input.setGeometry(QtCore.QRect(290, 90, 512, 512))
        self.hough_input.setStyleSheet("border: 4px solid black;\n"
"")
        self.hough_input.setText("")
        self.hough_input.setScaledContents(True)
        self.hough_input.setAlignment(QtCore.Qt.AlignCenter)
        self.hough_input.setObjectName("hough_input")
        self.hough_output = QtWidgets.QLabel(self.PassTab)
        self.hough_output.setGeometry(QtCore.QRect(830, 90, 512, 512))
        self.hough_output.setStyleSheet("border: 4px solid black;\n"
"")
        self.hough_output.setText("")
        self.hough_output.setScaledContents(True)
        self.hough_output.setAlignment(QtCore.Qt.AlignCenter)
        self.hough_output.setObjectName("hough_output")
        self.FilterLabel_3 = QtWidgets.QLabel(self.PassTab)
        self.FilterLabel_3.setGeometry(QtCore.QRect(20, 130, 241, 31))
        self.FilterLabel_3.setStyleSheet("font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 30px;\n"
"color: black;\n"
"background-color:transparent;\n"
"border-color: transparent")
        self.FilterLabel_3.setText("")
        self.FilterLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.FilterLabel_3.setObjectName("FilterLabel_3")
        self.Filtering_3 = QtWidgets.QWidget(self.PassTab)
        self.Filtering_3.setGeometry(QtCore.QRect(20, 170, 241, 221))
        self.Filtering_3.setStyleSheet("QWidget{\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"}")
        self.Filtering_3.setObjectName("Filtering_3")
        self.CircleButton = QtWidgets.QPushButton(self.Filtering_3)
        self.CircleButton.setGeometry(QtCore.QRect(10, 90, 221, 51))
        self.CircleButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.CircleButton.setObjectName("CircleButton")
        self.LinesButton = QtWidgets.QPushButton(self.Filtering_3)
        self.LinesButton.setGeometry(QtCore.QRect(10, 30, 221, 51))
        self.LinesButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.LinesButton.setObjectName("LinesButton")
        self.ElipsesButton = QtWidgets.QPushButton(self.Filtering_3)
        self.ElipsesButton.setGeometry(QtCore.QRect(10, 150, 221, 51))
        self.ElipsesButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"font-family: Impact, Haettenschweiler, \'Arial Narrow Bold\', sans-serif;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: rgb(246, 247, 250);\n"
"}\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.ElipsesButton.setObjectName("ElipsesButton")
        self.tabWidget.addTab(self.PassTab, "")
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton.setGeometry(QtCore.QRect(1130, 20, 141, 61))
        self.BrowseButton.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"text-align: left;\n"
"font: 900 12pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover:!pressed{\n"
"    background-color: qlineargradient(x1: 0.5, y1: 1, x2: 0.5, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/UploadIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BrowseButton.setIcon(icon3)
        self.BrowseButton.setIconSize(QtCore.QSize(50, 50))
        self.BrowseButton.setObjectName("BrowseButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.outputImageLabel.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel.setText(_translate("MainWindow", "Input"))
        self.RefreshButton.setText(_translate("MainWindow", "Refresh"))
        self.ActiveContourButton.setText(_translate("MainWindow", "Apply Active Contour"))
        self.label_5.setText(_translate("MainWindow", "Alpha "))
        self.label_6.setText(_translate("MainWindow", "Beta"))
        self.label_7.setText(_translate("MainWindow", "Gamma"))
        self.label_8.setText(_translate("MainWindow", "Sigma"))
        self.label_9.setText(_translate("MainWindow", "No. Of Iterations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FilterTab), _translate("MainWindow", "Filter"))
        self.outputImageLabel_2.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel_2.setText(_translate("MainWindow", "Input"))
        self.PrewittButton.setText(_translate("MainWindow", "Prewitt Edge Technique"))
        self.label.setText(_translate("MainWindow", "Prewitt"))
        self.label_2.setText(_translate("MainWindow", "Robert"))
        self.RobetButton.setText(_translate("MainWindow", "Robert Edge Technique"))
        self.label_3.setText(_translate("MainWindow", "Sobel"))
        self.SobelButton.setText(_translate("MainWindow", "Sobel Edge Technique"))
        self.label_4.setText(_translate("MainWindow", "Canny"))
        self.CannyButton.setText(_translate("MainWindow", "Canny Edge Technique"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EdgeDetection), _translate("MainWindow", "Edge Detection"))
        self.outputImageLabel_7.setText(_translate("MainWindow", "Output "))
        self.inputImageLabel_11.setText(_translate("MainWindow", "Input"))
        self.CircleButton.setText(_translate("MainWindow", "Apply Hough Circles"))
        self.LinesButton.setText(_translate("MainWindow", "Apply Hough Lines"))
        self.ElipsesButton.setText(_translate("MainWindow", "Apply Hough Elipses"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PassTab), _translate("MainWindow", "Hough Transform"))
        self.BrowseButton.setText(_translate("MainWindow", "Upload Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
